# The URL the site will be built for
base_url = "https://recipes4life.netlify.app"

# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = true

theme = "anatole-zola"

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = true

title = "Recipes4Life"
description = "Recipes. Plain And Simple."
base_url = "https://recipes4life.netlify.app"
default_language = "en"

[extra]
# Put all your custom variables here
taxonomies = [
  {name = "tags"},
]

[extra.show]
tags = true
links = true


[translations.en]
about = "About"
home = "Home"
tags = "Tags"
archive = "Archive"
links = "Links"
next_page = "Next Page"
last_page = "Last Page"

[translations.zh]
home = "首页"
about = "关于"
tags = "标签"
archive = "归档"
links = "友链"
next_page = "下一页"
last_page = "上一页"
